import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      description: 'Step-by-step how-tos for the Korevel Xaurus knowledge base.',
      collapsed: false,
      link: {type: 'generated-index', slug: '/guides'},
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
  ],
  docsSidebar: [
    {
      type: 'category',
      label: 'Reference',
      description: 'Look-up reference for tools, syntax, configuration, and commands.',
      collapsed: false,
      link: {type: 'generated-index', slug: '/reference'},
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
  bookSidebar: [
    {
      type: 'category',
      label: 'Engineering Handbook',
      description: 'A six-chapter handbook for day-to-day software engineering.',
      collapsed: false,
      link: {type: 'generated-index', slug: '/book'},
      items: [{type: 'autogenerated', dirName: 'book'}],
    },
  ],
};

export default sidebars;
